basePath: /api
definitions:
  api.message:
    properties:
      message:
        type: string
    type: object
  product.PreAddProduct:
    properties:
      category:
        type: string
      description:
        type: string
      image_link:
        type: string
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
  product.Product:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: string
      image_link:
        type: string
      name:
        type: string
      original_price:
        type: integer
      price:
        type: integer
      quantity:
        type: integer
    type: object
  user.Card:
    properties:
      balance:
        type: integer
      card_number:
        type: string
      id:
        type: string
      owner_id:
        type: string
    type: object
  user.PreLoginUser:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  user.PreSignUpUser:
    properties:
      full_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  user.User:
    properties:
      full_name:
        type: string
      id:
        type: string
      is_admin:
        type: boolean
      password:
        type: string
      phone_number:
        type: string
    type: object
  user.UserCard:
    properties:
      balance:
        type: integer
      card_number:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: khasanovasumbula@gmail.com
    name: Sunbula Hasanova
    url: https://t.me/Neverland_MJ
  description: online meva va poliz mahsulotlari sotiladigan magazen APIsi
  title: Arzon-market API
  version: "1.0"
paths:
  /add/card:
    post:
      consumes:
      - application/json
      description: user o'zining plastik kartasini kiritishi
      parameters:
      - description: Card info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.Card'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: plastik karta qo'shish
      tags:
      - user
  /admin/add/list/product:
    post:
      consumes:
      - application/json
      description: bir nechta produktalarni qo'shish
      parameters:
      - description: Product info
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/product.PreAddProduct'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: produktalar qo'shish
      tags:
      - admin
  /admin/add/product:
    post:
      consumes:
      - application/json
      description: bitta produkta qo'shish
      parameters:
      - description: Product info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/product.PreAddProduct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: produkta qo'shish
      tags:
      - admin
  /admin/users:
    get:
      description: hamma userlar ro'yxatini chiqarish
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserCard'
            type: array
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: hamma userlar ro'yxati
      tags:
      - admin
  /auth/login:
    post:
      consumes:
      - application/json
      description: user login qilishi
      parameters:
      - description: User info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.PreLoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: sign in
      tags:
      - auth
  /auth/logout:
    delete:
      description: user log out qilishi
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: log out
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: user registratsiyadan o'tishi
      parameters:
      - description: User info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.PreSignUpUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: sign up
      tags:
      - auth
  /buy/:
    get:
      description: produkta sotib olish
      parameters:
      - description: product name
        in: query
        name: name
        required: true
        type: string
      - description: product quantity
        in: query
        name: quantity
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: buy product
      tags:
      - user
  /product/{id}:
    get:
      description: bitta produkta haqida ma'lumotlarni olish
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: produkta
      tags:
      - public
  /product/list:
    get:
      description: barcha produktalarni ko'rsatish
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.message'
      summary: hamma produktalarni listi
      tags:
      - public
swagger: "2.0"
